"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .create_animal import *
from .create_living_things import *
from .create_new_bird import *
from .delete_animals_by_id import *
from .get_all_animals import *
from .get_all_birds import *
from .get_all_living_things import *
from .get_animals_by_id import *
from .update_animals_by_id import *

__all__ = ["CreateAnimalRequestBody","CreateAnimalResponse","CreateLivingThingsResponse","CreateNewBirdResponse","CreateNewBirdResponseBody","DeleteAnimalsByIDRequest","DeleteAnimalsByIDResponse","GetAllAnimalsRequest","GetAllAnimalsResponse","GetAllBirdsResponse","GetAllLivingThings1","GetAllLivingThings2","GetAllLivingThingsAnimalsMeta","GetAllLivingThingsPagination","GetAllLivingThingsRequest","GetAllLivingThingsResponse","GetAnimalsByIDRequest","GetAnimalsByIDResponse","Meta","One","Pagination","Two","UpdateAnimalsByIDRequest","UpdateAnimalsByIDResponse"]
