"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Any, Optional, Union



@dataclasses.dataclass
class GetAllLivingThingsRequest:
    filter: Optional[list[Any]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'filter', 'style': 'form', 'explode': True }})
    r"""include all filters"""
    




@dataclasses.dataclass
class GetAllLivingThings200ApplicationJSON:
    r"""OK"""
    




@dataclasses.dataclass
class GetAllLivingThingsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    get_all_living_things_200_application_json_object: Optional[Union[]] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

