"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import birds as shared_birds
from ..shared import error as shared_error
from typing import Optional



@dataclasses.dataclass
class GetAllBirdsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    birds: Optional[list[shared_birds.Birds]] = dataclasses.field(default=None)
    r"""OK"""
    error: Optional[shared_error.Error] = dataclasses.field(default=None)
    r"""Internal Server Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

