"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import animals as shared_animals
from typing import Optional


@dataclasses.dataclass
class GetAnimalsByIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    animals: Optional[shared_animals.Animals] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    per_page: Optional[int] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'perPage', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetAnimalsByIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    animals: Optional[shared_animals.Animals] = dataclasses.field(default=None)
    r"""OK"""
    

